language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - Gemfile
  - Gemfile.ruby1.8.7

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: Gemfile.ruby1.8.7
    - rvm: 1.9.3
      gemfile: Gemfile.ruby1.8.7